-- Warming-ups per wedstrijdtype in de workout-bibliotheek, als eigen vorm
-- 'warmup'. De onderbouwing staat in docs/warming-up-per-wedstrijdtype.md.
--
-- Een blok met burstSeconds begint met een burst van zoveel seconden en rijdt de
-- rest op zijn doel; zo blijft elk blok een heel aantal minuten
-- (src/lib/training/workouts.ts).
--
-- intensity is 'endurance' en niet 'recovery': dropShortRecoveryRides gooit
-- korte herstelritten uit een schema.

alter table public.training_workout_templates
  drop constraint if exists training_workout_templates_form_check;

alter table public.training_workout_templates
  add constraint training_workout_templates_form_check
  check (form in (
    'herstel','duur','tempo','sweetspot','drempel','vo2max','anaeroob','sprint','test','warmup'
  ));

insert into public.training_workout_templates
  (form, title, description, duration_minutes, intensity, target_type, structure_json, is_standard)
select
  v.form, v.title, v.description, v.duration_minutes, v.intensity, v.target_type, v.structure_json, true
from (values
  ('warmup', 'Warming-up tijdrit', 'Voor een tijdrit: lang op tempo komen, drie lichte versnellingen.', 25, 'endurance', 'power', '[{"label":"Inrijden","durationMinutes":5,"target":"50-60%","notes":"Rustig op gang komen.","intensity":"endurance"},{"label":"Opbouw","durationMinutes":4,"target":"60-75%","notes":"Geleidelijk oplopen.","intensity":"endurance"},{"label":"Tempo","durationMinutes":3,"target":"80-90%","notes":"Soepel, hoge cadans.","intensity":"tempo"},{"label":"Wedstrijdtempo","durationMinutes":2,"target":"95-100%","notes":"Het tempo van de tijdrit.","intensity":"threshold"},{"label":"Los","durationMinutes":3,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Opener","durationMinutes":1,"target":"105-115%","notes":"Net boven wedstrijdtempo.","intensity":"vo2max"},{"label":"Los","durationMinutes":2,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Burst 1/3","durationMinutes":1,"target":"50-55%","notes":"6 sec versnellen, niet voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 2/3","durationMinutes":1,"target":"50-55%","notes":"6 sec versnellen, niet voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 3/3","durationMinutes":1,"target":"50-55%","notes":"6 sec versnellen, niet voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Tot de start","durationMinutes":2,"target":"50-55%","notes":"Rustig doortrappen tot de start.","intensity":"recovery"}]'::jsonb),
  ('warmup', 'Warming-up scratch', 'Voor een korte race met een harde start.', 20, 'endurance', 'power', '[{"label":"Inrijden","durationMinutes":5,"target":"50-60%","notes":"Rustig op gang komen.","intensity":"endurance"},{"label":"Opbouw","durationMinutes":4,"target":"65-80%","notes":"Geleidelijk oplopen.","intensity":"endurance"},{"label":"Drempel","durationMinutes":2,"target":"90-100%","notes":"Soepel, hoge cadans.","intensity":"threshold"},{"label":"Los","durationMinutes":2,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Opener","durationMinutes":1,"target":"110-120%","notes":"Het tempo van de start.","intensity":"vo2max"},{"label":"Los","durationMinutes":2,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Burst 1/3","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 2/3","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 3/3","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Tot de start","durationMinutes":1,"target":"50-55%","notes":"Rustig doortrappen tot de start.","intensity":"recovery"}]'::jsonb),
  ('warmup', 'Warming-up puntenrace', 'Voor een race die op sprints wordt beslist.', 21, 'endurance', 'power', '[{"label":"Inrijden","durationMinutes":5,"target":"50-60%","notes":"Rustig op gang komen.","intensity":"endurance"},{"label":"Opbouw","durationMinutes":4,"target":"65-80%","notes":"Geleidelijk oplopen.","intensity":"endurance"},{"label":"Drempel","durationMinutes":2,"target":"90-100%","notes":"Soepel, hoge cadans.","intensity":"threshold"},{"label":"Los","durationMinutes":2,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Opener","durationMinutes":1,"target":"110-120%","notes":"Het tempo van de start.","intensity":"vo2max"},{"label":"Los","durationMinutes":2,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Burst 1/4","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 2/4","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 3/4","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 4/4","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Tot de start","durationMinutes":1,"target":"50-55%","notes":"Rustig doortrappen tot de start.","intensity":"recovery"}]'::jsonb),
  ('warmup', 'Warming-up ploegentijdrit', 'Voor een ploegentijdrit: kopbeurten en herstel in het wiel.', 25, 'endurance', 'power', '[{"label":"Inrijden","durationMinutes":5,"target":"50-60%","notes":"Rustig op gang komen.","intensity":"endurance"},{"label":"Opbouw","durationMinutes":4,"target":"60-80%","notes":"Geleidelijk oplopen.","intensity":"endurance"},{"label":"Tempo","durationMinutes":3,"target":"85-95%","notes":"Soepel, hoge cadans.","intensity":"tempo"},{"label":"Los","durationMinutes":2,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Kopbeurt 1/2","durationMinutes":1,"target":"110-120%","notes":"Als op kop van de trein.","intensity":"vo2max"},{"label":"In het wiel 1/2","durationMinutes":1,"target":"80-85%","notes":"Herstellen op tempo.","intensity":"tempo"},{"label":"Kopbeurt 2/2","durationMinutes":1,"target":"110-120%","notes":"Als op kop van de trein.","intensity":"vo2max"},{"label":"In het wiel 2/2","durationMinutes":1,"target":"80-85%","notes":"Herstellen op tempo.","intensity":"tempo"},{"label":"Los","durationMinutes":3,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Burst 1/2","durationMinutes":1,"target":"50-55%","notes":"6 sec versnellen, niet voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 2/2","durationMinutes":1,"target":"50-55%","notes":"6 sec versnellen, niet voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Tot de start","durationMinutes":2,"target":"50-55%","notes":"Rustig doortrappen tot de start.","intensity":"recovery"}]'::jsonb),
  ('warmup', 'Warming-up lange wedstrijd', 'Voor een wedstrijd van anderhalf uur of langer: kort, om energie te sparen.', 12, 'endurance', 'power', '[{"label":"Inrijden","durationMinutes":5,"target":"50-60%","notes":"Rustig op gang komen.","intensity":"endurance"},{"label":"Opbouw","durationMinutes":3,"target":"65-75%","notes":"Geleidelijk oplopen.","intensity":"endurance"},{"label":"Drempel","durationMinutes":1,"target":"90-100%","notes":"Even op wedstrijdtempo.","intensity":"threshold"},{"label":"Los","durationMinutes":1,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Burst","durationMinutes":1,"target":"50-55%","notes":"6 sec versnellen, niet voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Tot de start","durationMinutes":1,"target":"50-55%","notes":"Rustig doortrappen tot de start.","intensity":"recovery"}]'::jsonb),
  ('warmup', 'Warming-up kort', 'Tien minuten, voor als er weinig tijd is.', 10, 'endurance', 'power', '[{"label":"Inrijden","durationMinutes":3,"target":"50-60%","notes":"Rustig op gang komen.","intensity":"endurance"},{"label":"Opbouw","durationMinutes":3,"target":"65-85%","notes":"Geleidelijk oplopen.","intensity":"endurance"},{"label":"Opener","durationMinutes":1,"target":"100-110%","notes":"Even op wedstrijdtempo.","intensity":"vo2max"},{"label":"Los","durationMinutes":1,"target":"50-55%","notes":"Losdraaien.","intensity":"recovery"},{"label":"Burst 1/2","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6},{"label":"Burst 2/2","durationMinutes":1,"target":"50-55%","notes":"6 sec voluit. Daarna losdraaien.","intensity":"recovery","burstSeconds":6}]'::jsonb)
) as v(form, title, description, duration_minutes, intensity, target_type, structure_json)
on conflict (form, title) where is_standard do update
set
  description = excluded.description,
  duration_minutes = excluded.duration_minutes,
  intensity = excluded.intensity,
  target_type = excluded.target_type,
  structure_json = excluded.structure_json,
  updated_at = now();

notify pgrst, 'reload schema';
